
-- descomentar para crear la base de datos 
/*CREATE DATABASE systemhtours; */


/*..................................MODULO DE CUENTAS........................................*/
/*............................LA ALEXA Y EL KEVIN............................................*/
/*..............................1-CREAR CUENTA...............................................*/
/*..............................1.1-CLASIFICACION............................................*/
/*...........................................................................................*/

CREATE TABLE TBL_CLASIFICACIONES(
  COD_CLASIFICACION  BIGINT       PRIMARY KEY AUTO_INCREMENT  COMMENT 'CODIGO ID DE LA LLAVE PRIMARIA'
, NATURALEZA         VARCHAR(255) NOT NULL                    COMMENT 'NATURALEZA DE  LA CUENTA'
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


CREATE TABLE TBL_PERIODOS (
   `COD_PERIODO`     BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
  ,`COD_USUARIO`      BIGINT NOT NULL COMMENT 'FORANEA PARA INDENTIFICAR QUE USUARIO EJECUTO EL CIERRE DE MES' 
  ,`FEC_PERIODO`     DATETIME NOT NULL COMMENT 'FECHA EN QUE SE REALIZO' 
  ,`NOM_PERIODO`     VARCHAR(100) NOT NULL COMMENT 'Nombre del periodo'
  ,`FEC_INI`         DATETIME  NOT NULL  COMMENT 'FECHA DE  CONTABLIZACION INICIAL DEL PERIODO'
  ,`FEC_FIN`         DATETIME  NOT NULL  COMMENT 'FECHA DE FINALIZACION DEL PERIODO'
  ,`ESTADO`          ENUM('ACTIVO','CERRADO')  COMMENT 'ESTADO DEL PERIODO'
) ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE `tbl_ms_usuarios` (
  `COD_USUARIO` bigint(20) NOT NULL,
  `USUARIO` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `NOM_USR` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `EST_USUARIO` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `COD_ROL` bigint(20) NOT NULL,
  `FEC_ULTIMA_CONEXION` date NOT NULL,
  `PRE_CONTESTADAS` bigint(20) NOT NULL,
  `PRIMER_INGRESO` bigint(20) NOT NULL,
  `FECH_VENCIMIENTO` date NOT NULL,
  `CORREO_ELECTRONICO` varchar(50) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Indices de la tabla `tbl_ms_usuarios`
--
ALTER TABLE `tbl_ms_usuarios`
  ADD PRIMARY KEY (`COD_USUARIO`),
  ADD KEY `FK_USRROL` (`COD_ROL`);


ALTER TABLE
TBL_PERIODOS
ADD CONSTRAINT FK_PERUSU
FOREIGN  KEY tbl_periodos(COD_USUARIO)
REFERENCES tbl_ms_usuarios(COD_USUARIO) ON DELETE CASCADE;

  

CREATE TABLE TBL_CUENTAS(
  COD_CUENTA    BIGINT       PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO ID DE LA LLAVE PRIMARIA'
, COD_CLASIFICACION BIGINT                              COMMENT 'LLAVE FORANEA DE LA TABLA CLASIFICACION'
, NUM_CUENTA    VARCHAR(255) NOT NULL                   COMMENT 'NUMERO DE LA CUENTA'
, NOM_CUENTA    VARCHAR(255) NOT NULL                   COMMENT 'NOMBRE DE LA CUENTA'
,CONSTRAINT `FK_CUECLA` FOREIGN KEY (`COD_CLASIFICACION`) REFERENCES `TBL_CLASIFICACIONES` (`COD_CLASIFICACION`) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;







CREATE TABLE TBL_SUBCUENTAS(
  COD_SUBCUENTA   BIGINT     PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO ID DE LA LLAVE PRIMARIA'
, COD_CLASIFICACION BIGINT                              COMMENT 'LLAVE FORANEA DE LA TABLA CLASIFICACION'
, NUM_SUBCUENTA VARCHAR(255) NOT NULL                   COMMENT 'NUMERO DE LA CUENTA'
, NOM_SUBCUENTA VARCHAR(255) NOT NULL                   COMMENT 'NOMBRE DE LA CUENTA'
, COD_CUENTA    BIGINT                                  COMMENT 'CODIGO ID DE LA LLAVE PRIMARIA'
,CONSTRAINT `FK_SUBCLA` FOREIGN KEY (`COD_CLASIFICACION`) REFERENCES `TBL_CLASIFICACIONES` (`COD_CLASIFICACION`) ON DELETE CASCADE
,CONSTRAINT `FK_SUBCUE` FOREIGN KEY (`COD_CUENTA`) REFERENCES `TBL_CUENTAS` (`COD_CUENTA`) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;



/*..................................MODULO DE PERIODO........................................*/
/*............................LA ALEXA Y EL KEVIN............................................*/
/*..............................1-LIBRIO DIARIO..............................................*/
/*..............................2-LIBRIO MAYOR...............................................*/
/*...........................................................................................*/
/*...........................................................................................*/
/*...........................................................................................*/
CREATE TABLE TBL_ESTADOS_SUBCUENTAS(
 COD_ESTADO BIGINT           PRIMARY KEY  AUTO_INCREMENT        COMMENT 'LLAVE PRIMARIA DE LA TABLA ESTADO'
,COD_SUBCUENTA BIGINT                                           COMMENT 'LLAVE FORANEA DE LA TABLA SUBCUENTAS'
,EST_SUBCUENTAS ENUM('INGRESADA', 'PENDIENTE', 'PROCESADA')            COMMENT 'DESCRIPCION DEL ESTADO EN EL QUE SE ENCUENTRA LA TRANSACCION'
,CONSTRAINT `FK_ESTSUB` FOREIGN KEY (`COD_SUBCUENTA`) REFERENCES `TBL_SUBCUENTAS` (`COD_SUBCUENTA`) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE TBL_LIBROS_DIARIOS(
  COD_LIBDIARIO  BIGINT      PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO ID DE LA LLAVE PRIMARIA'
, COD_CUENTA    BIGINT                                  COMMENT 'CODIGO ID DE LA LLAVE PRIMARIA'
, COD_SUBCUENTA BIGINT                                  COMMENT 'CODIGO ID DE LA LLAVE PRIMARIA'
, COD_ESTADO    BIGINT                                  COMMENT 'CODIGO ID DE LA LLAVE PRIMARIA'
, NUM_SUBCUENTA VARCHAR(255) NOT NULL                   COMMENT 'NUMERO DE LA SUBCUENTA'
, NOM_SUBCUENTA VARCHAR(255) NOT NULL                   COMMENT 'NOMBRE DE LA SUBCUENTA'
, SAL_DEBE    DECIMAL (5,2) NOT NULL                    COMMENT 'SALDO DEBE DE LA CUENTA'
, SAL_HABER   DECIMAL (5,2) NOT NULL                    COMMENT 'SALDO HABER DE LA CUENTA'
, FEC_LIBDIARIO DATETIME NOT NULL                       COMMENT 'FECHA QUE SE REGISTRA LA TUPLA'
,CONSTRAINT `FK_LIBDCUE` FOREIGN KEY (`COD_CUENTA`) REFERENCES `TBL_CUENTAS` (`COD_CUENTA`) ON DELETE CASCADE
,CONSTRAINT `FK_LIBDSUB` FOREIGN KEY (`COD_SUBCUENTA`) REFERENCES `TBL_SUBCUENTAS` (`COD_SUBCUENTA`) ON DELETE CASCADE
,CONSTRAINT `FK_LIBDEST` FOREIGN KEY (`COD_ESTADO`) REFERENCES `TBL_ESTADOS_SUBCUENTAS` (`COD_ESTADO`) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


CREATE TABLE TBL_ESTADOS_CUENTAS(
 COD_ESTCUENTA BIGINT           PRIMARY KEY  AUTO_INCREMENT       COMMENT 'LLAVE PRIMARIA DE LA TABLA ESTADO'
,COD_CUENTA BIGINT                                                COMMENT 'LLAVE FORANEA DE LA TABLA SUBCUENTAS'                                           
,EST_CUENTA ENUM('INGRESADA', 'PENDIENTE', 'PROCESADA')               COMMENT 'DESCRIPCION DEL ESTADO EN EL QUE SE ENCUENTRA LA TRANSACCION'
,CONSTRAINT `FK_ESTCUE` FOREIGN KEY (`COD_CUENTA`) REFERENCES `TBL_CUENTAS` (`COD_CUENTA`) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;




CREATE TABLE TBL_LIBROS_MAYORES(  
  COD_LIBMAYOR BIGINT       PRIMARY KEY AUTO_INCREMENT COMMENT 'CODIGO ID DE LA LLAVE PRIMARIA'
, COD_CUENTA  BIGINT                                  COMMENT 'CODIGO ID DE LA LLAVE PRIMARIA'
, COD_CLASIFICACION BIGINT                         COMMENT 'LLAVE FORANEA DE LA TABLA CLASIFICACION'
, COD_PERIODO BIGINT                                 COMMENT 'LLAVE FORANEA DE LA TABLA PERIODO'
, COD_ESTCUENTA BIGINT                                COMMENT 'LLAVE FORANEA DE LA TABLA ESTADO DE CUENTAS'
, NUM_CUENTA   VARCHAR(255) NOT NULL                   COMMENT 'NUMERO DE LA CUENTA'
, NOM_CUENTA   VARCHAR(255) NOT NULL                   COMMENT 'NOMBRE DE LA CUENTA'
, SAL_DEBE   DECIMAL (5,2) NOT NULL                   COMMENT 'SALDO DEBE DE LA CUENTA'
, SAL_HABER  DECIMAL (5,2) NOT NULL                   COMMENT 'SALDO HABER DE LA CUENTA'
, FEC_LIBMAYOR DATETIME NOT NULL                   COMMENT 'FECHA QUE SE REGISTRA LA TUPLA'
,CONSTRAINT `FK_LIBMCUE` FOREIGN KEY (`COD_CUENTA`) REFERENCES `TBL_CUENTAS` (`COD_CUENTA`) ON DELETE CASCADE
,CONSTRAINT `FK_LIBMCLA` FOREIGN KEY (`COD_CLASIFICACION`) REFERENCES `TBL_CLASIFICACIONES` (`COD_CLASIFICACION`) ON DELETE CASCADE
,CONSTRAINT `FK_LIBMPER` FOREIGN KEY (`COD_PERIODO`) REFERENCES `TBL_PERIODOS` (`COD_PERIODO`) ON DELETE CASCADE
,CONSTRAINT `FK_LIBMEST` FOREIGN KEY (`COD_ESTCUENTA`) REFERENCES `TBL_ESTADOS_CUENTAS` (`COD_ESTCUENTA`) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;


CREATE TABLE `tbl_ms_parametros` (
  `COD_PARAMETRO` bigint NOT NULL,
  `PARAMETRO` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `VALOR` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `COD_USUARIO` bigint(20) NOT NULL,
  `FECH_CREACION` date NOT NULL,
  `FECH_MODIFICACION` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Indices de la tabla `tbl_ms_parametros`
--


ALTER TABLE `tbl_ms_parametros`
  ADD PRIMARY KEY (`COD_PARAMETRO`);
--
ALTER TABLE `tbl_ms_parametros`
  ADD KEY `FK_PARUSR` (`COD_USUARIO`);

/*..................................MODULO DE ESTADO FINANCIERO........................................*/
/*.................................ZOILA Y EMERSON............................................*/
/*..............................1-TBL_ESTADOS_RESULTADOS...............................................*/
/*..............................2-TBL_BALANCES_GENERALES............................................*/
/*..............................3.TBL_SALDOS_BALANCE.................................................*/
/*..............................4.TBL_COMPROBANTE.................................................*/
/*...............................5.TBL_PERIODO....................................................*/
CREATE TABLE TBL_ESTADOS_RESULTADOS(
    `COD_ESTRESULTADO`   BIGINT PRIMARY KEY AUTO_INCREMENT  NOT NULL
    ,`COD_LIBMAYOR`  BIGINT 
    ,`COD_PERIODO`   BIGINT
    ,`COD_PARAMETRO`  BIGINT 
    ,`EMPRESA`       VARCHAR(50) NOT NULL COMMENT 'NOMBRE DE LA EMPRESA'
    ,`FEC_ESTADO`     DATETIME NOT NULL COMMENT 'FECHA EN LA QUE SE HACE EL ESTADO DE RESULTADO'
   /* `VENTAS`        DECIMAL(7,2) NOT NULL COMMENT 'LAS VENTAS AL CONTANDO DE LA EMPRESA'
    `DESC_VENTAS`   DECIMAL(7,2) NOT NULL COMMENT 'DESCUENTOS SOBRE VENTAS', */
    ,`VEN_NETAS`     DECIMAL(7,2) NOT NULL COMMENT 'Ventas netas = Ventas - Descuentos'
   /* ,`SUELDOS`       INT NOT NULL COMMENT 'SUELDOS QUE SE PAGAN A VENDEDORES'
    ,`OTR_GAST`      INT NOT NULL COMMENT 'OTROS GASTOS O GASTOS QUE NOS SIRVEN PARA FABRICAR', */
    ,`COS_VENTAS`   DECIMAL(7,2) NOT NULL COMMENT 'TOTAL COSTO DE VENTAS= SUELDOS+COST_VENTAS',
    `UTI_BRUTA`    DECIMAL(7,2) NOT NULL COMMENT 'VENTAS NETAS - COSTOS DE VENTAS = UTILIDAD BRUTA DE LAS VENTAS',
   /* `GAST_ADMIN`    INT NOT NULL COMMENT 'PUEDE SER SUELDOS QUE SE PAGAN A LOS QUE ADMINISTRAN LA EMPRESA(FISCALMENTE TIENE DIFERENTE TRATATAMIENTO A MANO DE OBRA',
    `GAST_VENTA`    INT NOT NULL COMMENT 'GASTOS DE PUBLICIDAD, GASTOS DE MARKETING, GASTO QUE NOSOSTROS UTILIZAMOS PARA PODER VENDER', */
    `TOT_GASTOS`    DECIMAL(7,2) NOT NULL COMMENT 'GASTOS TOTALES ES GASTOS ADMINISTRATIVOS + GASTO DE VENTAS',
    `UTI_ANTIMP` DECIMAL(7,2) NOT NULL COMMENT 'UTILIDAD ANTES DE IMPUESTO =  UTILDAD BRUTA-TOTALDEGASTOS',
    `IMP_UTILIDAD`  DECIMAL(7,2) NOT NULL COMMENT 'ESTE ES EL IMPUESTO A LA UTILIDAD ES EL 10% EN HONDURAS DE UTIL_IMP',
    `UTI_NETA`   DECIMAL(7,2) NOT NULL COMMENT 'LA UTILIDAD NETA= UTIL_IMP-IMP_UTILIDAD'
     ,CONSTRAINT `FK_ESTLIBMAYOR` FOREIGN KEY (`COD_LIBMAYOR`) REFERENCES `TBL_LIBROS_MAYORES` (`COD_LIBMAYOR`) ON DELETE CASCADE
     ,CONSTRAINT `FK_ESTPER` FOREIGN KEY (`COD_PERIODO`) REFERENCES `TBL_PERIODOS` (`COD_PERIODO`) ON DELETE CASCADE
     ,CONSTRAINT `FK_ESTPAR` FOREIGN KEY (`COD_PARAMETRO`) REFERENCES `tbl_ms_parametros` (`COD_PARAMETRO`) ON DELETE CASCADE 
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;




CREATE TABLE `tbl_balances_generales` (
  `COD_BALANCE` bigint NOT NULL AUTO_INCREMENT,
  `COD_LIBMAYOR` bigint NOT NULL,
  `EMPRESA` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `FEC_BALANCE` datetime NOT NULL,
  `TOT_ACTIVO` int NOT NULL,
  `TOT_PASIVO` int NOT NULL,
  `TOT_PATRIMONIO` int NOT NULL,
  PRIMARY KEY (`COD_BALANCE`),
  KEY `FK_BLGLIBMAYOR` (`COD_LIBMAYOR`),
  CONSTRAINT `FK_BLGLIBMAYOR` FOREIGN KEY (`COD_LIBMAYOR`) REFERENCES `TBL_LIBROS_MAYORES` (`COD_LIBMAYOR`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE TBL_SALDOS_BALANCES (
 `COD_SALDO`    BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
,`COD_BALANCE`  BIGINT NOT NULL
,`FEC_SALDOS`   DATETIME NOT NULL
,`TOT_ACTIVO`   INT NOT NULL
,`TOT_PASPAT`   INT NOT NULL COMMENT 'SUMA DE TOTAL DE PASIVO + TOTAL DE CAPITAL'
 ,CONSTRAINT `FK_ SALBLG` FOREIGN KEY (`COD_BALANCE`) REFERENCES `TBL_BALANCES_GENERALES` (`COD_BALANCE`) ON DELETE CASCADE
) ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;



/*
https://www.youtube.com/watch?v=pFXCU5l2ttc&t=307s

https://www.youtube.com/watch?v=lF-p6v405eY

https://www.youtube.com/results?search_query=sistema+contable+web+gratis

https://www.youtube.com/watch?v=2KrJMXfw_e8

https://www.youtube.com/watch?v=FeGB7JBplco

*/



CREATE TABLE TBL_COMPROBANTES(
  `COD_COMPROBANTE` BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL 
  ,`COD_LIBDIARIO`  BIGINT NOT NULL
  ,`FEC_COMPROBANTE`DATETIME NOT NULL
  ,`COMPROBANTE`    VARCHAR(255) NOT NULL
  ,`DES_COMPROBANTE`VARCHAR(100) NOT NULL
  ,CONSTRAINT `FK_COM_LIBDIARIO` FOREIGN KEY (`COD_LIBDIARIO`) REFERENCES `TBL_LIBROS_DIARIOS` (`COD_LIBDIARIO`) ON DELETE CASCADE
)ENGINE=INNODB
CHARACTER SET UTF8
COLLATE UTF8_UNICODE_CI;

CREATE TABLE `tbl_objetos` (
  `COD_OBJETO` bigint NOT NULL,
  `OBJETO` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `DES_OBJETO` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `TIP_OBJETO` varchar(15) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Indices de la tabla `tbl_objetos`
--
ALTER TABLE `tbl_objetos`
  ADD PRIMARY KEY (`COD_OBJETO`);


/*CREACION DE TABLAS MODULO SEGURIDAD BITACORA*/
Create table TBL_MS_BITACORAS (
 COD_BITACORA BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL
,FEC_REGISTRO DATETIME NOT NULL
,USR_REGISTRA VARCHAR(100) NOT NULL
,COD_USUARIOS BIGINT NOT NULL
,ACC_SISTEMA VARCHAR(100) NOT NULL
,DES_BITACORA VARCHAR(100) NOT NULL
,COD_OBJETO   BIGINT NOT NULL
,CONSTRAINT `FK_CODRB` FOREIGN KEY (`COD_USUARIOS`) REFERENCES `TBL_MS_USUARIOS` (`COD_USUARIO`) ON DELETE CASCADE
,CONSTRAINT `FK_BITOBJ` FOREIGN KEY (`COD_OBJETO`) REFERENCES `tbl_objetos` (`COD_OBJETO`) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;

CREATE TABLE `tbl_ms_hist_contraseña` (
  `COD_HIST`   BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL
  ,`COD_USUARIO` bigint NOT NULL
  ,`CONTRASEÑA` varchar(100) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;




-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `tbl_ms_preguntas`
--


CREATE TABLE `tbl_ms_preguntas` (
  `COD_PREGUNTA` bigint NOT NULL,
  `PREGUNTA` varchar(100) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `tbl_ms_preguntas_usuarios`
--



CREATE TABLE `tbl_ms_preguntas_usuarios` (
  `COD_PREUSR` bigint NOT NULL,
  `COD_PREGUNTA` bigint NOT NULL,
  `COD_USUARIO` bigint NOT NULL,
  `RESPUESTA` varchar(100) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `tbl_ms_roles`
--

CREATE TABLE `tbl_ms_roles` (
  `COD_ROL` bigint NOT NULL,
  `ROL` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `DES_ROL` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `CREADO_POR` varchar(100) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------


-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `tbl_objetos`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `tbl_permisos`
--


CREATE TABLE `tbl_permisos` (
  `COD_ROL` bigint NOT NULL,
  `COD_OBJETO` bigint NOT NULL,
  `PER_INSERCION` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
  `PER_ELIMINACION` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
  `PER_ACTUALIZACION` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
  `PER_CONSULTAR` varchar(1) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `tbl_roles_objetos`
--
CREATE TABLE `tbl_roles_objetos` (
  `COD_ROL` bigint NOT NULL,
  `COD_OBJETO` bigint NOT NULL,
  `PER_EDICION` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `PER_ELIMINAR` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `PER_ACTUALIZAR` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `FEC_CREACION` date NOT NULL,
  `CREADO_POR` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `FEC_MODIFICACION` date NOT NULL,
  `MOD_POR` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT 'MODIFICADO POR'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
--

-- Indices de la tabla `tbl_ms_hist_contraseña`
--
ALTER TABLE `tbl_ms_hist_contraseña`
  ADD KEY `FK_HISTUSR` (`COD_USUARIO`);

--


-- Indices de la tabla `tbl_ms_preguntas`
--
ALTER TABLE `tbl_ms_preguntas`
  ADD PRIMARY KEY (`COD_PREGUNTA`);

--
-- Indices de la tabla `tbl_ms_preguntas_usuarios`
--
ALTER TABLE `tbl_ms_preguntas_usuarios`
  ADD KEY `FK_PREGXUSER` (`COD_PREUSR`),
  ADD KEY `FK_PREUSRUSER` (`COD_USUARIO`);

--
-- Indices de la tabla `tbl_ms_roles`
--
ALTER TABLE `tbl_ms_roles`
  ADD PRIMARY KEY (`COD_ROL`);

--

--

--
-- Indices de la tabla `tbl_permisos`
--
ALTER TABLE `tbl_permisos`
  ADD KEY `FK_PERROLES` (`COD_ROL`),
  ADD KEY `FK_PEROBJ` (`COD_OBJETO`);

--
-- Indices de la tabla `tbl_roles_objetos`
--
ALTER TABLE `tbl_roles_objetos`
  ADD KEY `FK_ROLOBJ` (`COD_ROL`),
  ADD KEY `FK_OBJEROL` (`COD_OBJETO`);

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `tbl_ms_hist_contraseña`
--
ALTER TABLE `tbl_ms_hist_contraseña`
  ADD CONSTRAINT `FK_HISTUSR` FOREIGN KEY (`COD_USUARIO`) REFERENCES `tbl_ms_usuarios` (`COD_USUARIO`) ON DELETE CASCADE;

--
-- Filtros para la tabla `tbl_ms_parametros`
--
ALTER TABLE `tbl_ms_parametros`
  ADD CONSTRAINT `FK_PARUSR` FOREIGN KEY (`COD_USUARIO`) REFERENCES `tbl_ms_usuarios` (`COD_USUARIO`) ON DELETE CASCADE;

--
-- Filtros para la tabla `tbl_ms_preguntas_usuarios`
--
ALTER TABLE `tbl_ms_preguntas_usuarios`
  ADD CONSTRAINT `FK_PREUSER` FOREIGN KEY (`COD_USUARIO`) REFERENCES `tbl_ms_usuarios` (`COD_USUARIO`) ON DELETE CASCADE,
  ADD CONSTRAINT `FK_PREGUSRMSPRE` FOREIGN KEY (`COD_PREGUNTA`) REFERENCES `tbl_ms_preguntas` (`COD_PREGUNTA`) ON DELETE CASCADE;

--
-- Filtros para la tabla `tbl_ms_usuarios`
--
ALTER TABLE `tbl_ms_usuarios`
  ADD CONSTRAINT `FK_USRROL` FOREIGN KEY (`COD_ROL`) REFERENCES `tbl_ms_roles` (`COD_ROL`) ON DELETE CASCADE;

--
-- Filtros para la tabla `tbl_permisos`
--
ALTER TABLE `tbl_permisos`
  ADD CONSTRAINT `FK_PEROBJ` FOREIGN KEY (`COD_OBJETO`) REFERENCES `tbl_objetos` (`COD_OBJETO`) ON DELETE CASCADE,
  ADD CONSTRAINT `FK_PERROLES` FOREIGN KEY (`COD_ROL`) REFERENCES `tbl_ms_roles` (`COD_ROL`) ON DELETE CASCADE;

--
-- Filtros para la tabla `tbl_roles_objetos`
--
ALTER TABLE `tbl_roles_objetos`
  ADD CONSTRAINT `FK_ROLOBJ` FOREIGN KEY (`COD_OBJETO`) REFERENCES `tbl_objetos` (`COD_OBJETO`) ON DELETE CASCADE,
  ADD CONSTRAINT `FK_OBJEROL` FOREIGN KEY (`COD_ROL`) REFERENCES `tbl_ms_roles` (`COD_ROL`) ON DELETE CASCADE;
COMMIT;









/*

/*CREACION DE TABLAS MODULO REPORTES LIBRO MAYOR
Create table TBL_REPORTES_LM (
COD_REPORTE      BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL
,NOM_REPORTE     VARCHAR(50)   NOT NULL
,COD_LIBROMAYOR  BIGINT        NOT NULL
,FEC_REGISTRO    DATETIME      NOT NULL
,CONSTRAINT `FK_CODRLM` FOREIGN KEY (`COD_LIBROMAYOR`) REFERENCES `TBL_LIBRO_MAYOR` (`COD_LIBMAYOR`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*CREACION DE TABLAS MODULO REPORTES ESTADO DE RESULTADO
Create table TBL_REPORTES_ER (
COD_REPORTE BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL
,NOM_REPORTE VARCHAR(50) NOT NULL
,COD_ER BIGINT NOT NULL
,FEC_REGISTRO DATETIME NOT NULL
,CONSTRAINT `FK_CODRER` FOREIGN KEY (`COD_ER`) REFERENCES `TBL_ESTADOS_RESULTADOS` (`COD_ESTRESULTADO`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


/*CREACION DE TABLAS MODULO REPORTES BALANCE GENERAL
Create table TBL_REPORTES_BG (
COD_REPORTE BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL
,NOM_REPORTE VARCHAR(50) NOT NULL
,COD_BG BIGINT NOT NULL
,FEC_REGISTRO DATETIME NOT NULL
,CONSTRAINT `FK_CODRBG` FOREIGN KEY (`COD_BG`) REFERENCES `TBL_BALANCES_GENERALES` (`COD_BALANCE`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


*/
