
-- todos los procedimientos necesitan adaptarse a la nueva estructura de las base de datos

CREATE PROCEDURE PRC_CUENTAS(
   IN PV_NATURALEZA VARCHAR(255)
  ,IN PV_NOMBRE_CUENTA VARCHAR(255)
  ,IN PV_NUM_CUENTA VARCHAR(255)
  /*,IN PV_OPERACION VARCHAR(1)
  ,IN PB_FILA BIGINT */
)
BEGIN
DECLARE V_CODIGO VARCHAR(255);
DECLARE V_VALIDADORDEEXISTENCIA INT;
/*LLEVA FORANEA CON LA CLASIFICACION*/
/*Valida naturaleza*/
SELECT COD_CLASIFICACION FROM TBL_CLASIFICACIONES WHERE NATURALEZA = PV_NATURALEZA INTO V_CODIGO;
/*Valida existencia*/
select count(*) from tbl_cuentas where NUM_CUENTA =  CONCAT(V_CODIGO,'.',PV_NUM_CUENTA) INTO V_VALIDADORDEEXISTENCIA;
/*si NO existe*/
IF V_VALIDADORDEEXISTENCIA = 0 THEN

INSERT INTO tbl_cuentas
(COD_CLASIFICACION, NUM_CUENTA, NOM_CUENTA) 
VALUES (V_CODIGO, CONCAT(V_CODIGO,'.',PV_NUM_CUENTA), PV_NOMBRE_CUENTA);
/* Si existe despliega mensaje que esta duplicado */
ELSE
SELECT 'NUMERO DE CUENTA DUPLICADA';
END IF;
COMMIT;
END;



CREATE PROCEDURE PRC_SUBCUENTAS(
     IN PV_CLASIFICACION BIGINT
    ,IN PB_COD_CUENTA   BIGINT
    ,IN PV_NUM_SUBCUENTA  VARCHAR(255) /*Numero correlativo para el catagalo de cuentas*/
    ,IN PV_NOM_SUBCUENTA VARCHAR(255)
    ,IN PV_OPERACION VARCHAR(1)
    ,IN PV_FILA BIGINT
    )
BEGIN
DECLARE V_CODIGO VARCHAR(255);
DECLARE VALIDADORDEEXISTENCIA INT;
DECLARE V_NATURALEZA VARCHAR(255);
/* DECLARE V_FORANEA BIGINT; la llave foranea de cuentas*/
DECLARE V_CLASIFICACION BIGINT; /*La clasificacion de la cuentas*/
/* SE LE HACE UN SELECT A TODOS LAS CUENTAS POR LA NATURALEZA QUE SE ESPECIFIQUE PARA PRESENTARLE UNA LISTA AL USUARIO
Y QUE PUEDA ESCOGER COMO SUB CUENTA DE QUE CUENTA QUIERE CREAR UNA NUEVA SUBCUENTA */
IF PV_OPERACION = 1 THEN
SELECT NOM_CUENTA FROM tbl_cuentas WHERE cod_clasificacion =  PV_CLASIFICACION;

ELSEIF PV_OPERACION = 2 THEN 
SELECT COD_CLASIFICACION,NUM_CUENTA FROM tbl_cuentas  WHERE COD_CUENTA = PB_COD_CUENTA INTO V_CLASIFICACION,V_CODIGO;
select count(*) from tbl_subcuentas where NUM_SUBCUENTA =  CONCAT(V_CODIGO,'.',PV_NUM_SUBCUENTA) INTO VALIDADORDEEXISTENCIA;

  IF VALIDADORDEEXISTENCIA = 0 THEN
  INSERT INTO tbl_subcuentas
(COD_CLASIFICACION, NUM_SUBCUENTA, NOM_SUBCUENTA, COD_CUENTA) 
VALUES (V_CLASIFICACION,CONCAT(V_CODIGO,'.',PV_NUM_SUBCUENTA), PV_NOM_SUBCUENTA, PB_COD_CUENTA);

  else
  select "subcuenta duplicada";
  END IF;
END IF; 
COMMIT;
END;



