
/* 
    PB  = PARAMETRO BIGINT
 -- PV  = PARAMETRO VARCHAR
 -- PC  = PARAMETRO CHAR
 -- PEM = PARAMETRO ENUM
 -- PF  = PARAMETRO FECHA
 -- PMI = PARAMETRO MEDIUMINT 
 -- PMT = PARAMETRO MEDIUMTEXT
 -- PI  = PARAMETRO INT
 -- PD  = PARAMETRO DECIMAL
 -- PDB = PARAMETRO DOUBLE
 -- PMB = PARAMETRO MEDIUMBLOB
*/

CREATE PROCEDURE PRC_ESTADOS_CUENTAS(
   IN PB_COD_CUENTA BIGINT
  ,IN PEM_EST_CUENTA ENUM('INGRESADA', 'PENDIENTE', 'PROCESADA')
  ,IN PV_OPERACION VARCHAR (1)
  ,IN PB_FILA BIGINT 
)

BEGIN
START TRANSACTION;
IF PV_OPERACION = 1 THEN

INSERT INTO TBL_ESTADOS_CUENTAS
(COD_CUENTA,EST_CUENTA)
VALUES (PB_COD_CUENTA,  PEM_EST_CUENTA );

ELSEIF PV_OPERACION = 2 THEN

UPDATE TBL_ESTADOS_CUENTAS
SET COD_CUENTA = PB_COD_CUENTA , EST_CUENTA = PEM_EST_CUENTA
WHERE COD_ESTCUENTA = PB_FILA;

ELSEIF PV_OPERACION = 3 THEN

DELETE FROM TBL_ESTADOS_CUENTAS 
WHERE COD_ESTCUENTA = PB_FILA; 

ELSEIF PV_OPERACION = 4 THEN

SELECT * FROM TBL_ESTADOS_CUENTAS;

ELSEIF PV_OPERACION = 5 THEN
SELECT * FROM TBL_ESTADOS_CUENTAS WHERE COD_ESTCUENTA = PB_FILA;

END IF;
COMMIT;
END;


/* 
    PB  = PARAMETRO BIGINT
 -- PV  = PARAMETRO VARCHAR
 -- PC  = PARAMETRO CHAR
 -- PEM = PARAMETRO ENUM
 -- PF  = PARAMETRO FECHA
 -- PMI = PARAMETRO MEDIUMINT 
 -- PMT = PARAMETRO MEDIUMTEXT
 -- PI  = PARAMETRO INT
 -- PD  = PARAMETRO DECIMAL
 -- PDB = PARAMETRO DOUBLE
 -- PMB = PARAMETRO MEDIUMBLOB
*/



CREATE PROCEDURE PRC_LIBROS_MAYORES(
  
 IN PB_COD_CUENTA  BIGINT                                  
, IN PB_COD_CLASIFICACION BIGINT                         
, IN PB_COD_PERIODO BIGINT                               
, IN PB_COD_ESTCUENTA BIGINT                             
, IN PV_NUM_CUENTA   VARCHAR(255)               
, IN PV_NOM_CUENTA   VARCHAR(255) 
, IN PD_SAL_DEBE   DECIMAL (8,2) 
, IN PD_SAL_HABER  DECIMAL (8,2)  
  ,IN PV_OPERACION VARCHAR (1)
  ,IN PB_FILA BIGINT 
)

BEGIN
START TRANSACTION;
IF PV_OPERACION = 1 THEN

INSERT INTO TBL_LIBROS_MAYORES
(COD_CUENTA,COD_CLASIFICACION,COD_PERIODO,COD_ESTCUENTA,NUM_CUENTA,NOM_CUENTA,SAL_DEBE,SAL_HABER, FEC_LIBMAYOR)
VALUES (PB_COD_CUENTA,  PB_COD_CLASIFICACION, PB_COD_PERIODO, PB_COD_ESTCUENTA, PV_NUM_CUENTA, PV_NOM_CUENTA , PD_SAL_DEBE, PD_SAL_HABER, NOW());

ELSEIF PV_OPERACION = 2 THEN

UPDATE TBL_LIBROS_MAYORES
SET COD_CUENTA = PB_COD_CUENTA , COD_PERIODO = PB_COD_PERIODO,COD_ESTCUENTA =PB_COD_ESTCUENTA, NUM_CUENTA = PV_NUM_CUENTA,NOM_CUENTA = PV_NOM_CUENTA, SAL_DEBE = PD_SAL_DEBE, SAL_HABER = PD_SAL_HABER, FEC_LIBMAYOR=NOW()
WHERE COD_LIBMAYOR = PB_FILA;

ELSEIF PV_OPERACION = 3 THEN

DELETE FROM TBL_LIBROS_MAYORES 
WHERE COD_LIBMAYOR = PB_FILA; 

ELSEIF PV_OPERACION = 4 THEN

SELECT * FROM TBL_LIBROS_MAYORES;

ELSEIF PV_OPERACION = 5 THEN
SELECT * FROM TBL_LIBROS_MAYORES WHERE COD_LIBMAYOR = PB_FILA;

END IF;
COMMIT;
END;


/* 
    PB  = PARAMETRO BIGINT
 -- PV  = PARAMETRO VARCHAR
 -- PC  = PARAMETRO CHAR
 -- PEM = PARAMETRO ENUM
 -- PF  = PARAMETRO FECHA
 -- PMI = PARAMETRO MEDIUMINT 
 -- PMT = PARAMETRO MEDIUMTEXT
 -- PI  = PARAMETRO INT
 -- PD  = PARAMETRO DECIMAL
 -- PDB = PARAMETRO DOUBLE
 -- PMB = PARAMETRO MEDIUMBLOB
*/




CREATE PROCEDURE PRC_ms_patametros(
   IN PB_PARAMETRO BIGINT
  ,IN PV_VALOR VARCHAR(50)
  ,IN PB_COD_USR BIGINT
  ,IN PV_OPERACION VARCHAR (1)
  ,IN PB_FILA BIGINT 
)

BEGIN
START TRANSACTION;
IF PV_OPERACION = 1 THEN

INSERT INTO tbl_ms_parametros
(PARAMETRO,VALOR, COD_USR, FEC_CREACION, FEC_MODIFICACION )
VALUES (PB_PARAMETRO,  PV_VALOR, PB_COD_USR, NOW(), NOW());

ELSEIF PV_OPERACION = 2 THEN

UPDATE tbl_ms_parametros
SET PARAMETRO = PB_PARAMETRO , VALOR = PV_VALOR,FEC_CREACION=NOW(), FEC_MODIFICACION = NOW()
WHERE COD_PARAMETRO = PB_FILA;

ELSEIF PV_OPERACION = 3 THEN

DELETE FROM tbl_ms_parametros 
WHERE COD_PARAMETRO = PB_FILA; 

ELSEIF PV_OPERACION = 4 THEN

SELECT * FROM tbl_ms_parametros;

ELSEIF PV_OPERACION = 5 THEN
SELECT * FROM tbl_ms_parametros WHERE COD_PARAMETRO = PB_FILA;

END IF;
COMMIT;
END;






